# This file is part of https://github.com/kimght/LimbusCompanyRuMTL/blob/main/config.toml
# So clear structure of .toml file with syntax is not required, font parameters for files being readed via Regex


[[font_rules."Enemies*.json"]]
font = "bebas"
path = '$.dataList[*].name'

[[font_rules."StageChapterText*.json"]]
font = "bebas"
path = '$.dataList[*].company'

[[font_rules."StageChapterText*.json"]]
font = "bebas"
path = '$.dataList[*].area'

[[font_rules."StageChapterText*.json"]]
font = "bebas"
path = '$.dataList[*].chapter'

[[font_rules."SeasonTitle.json"]]
font = "bebas"
path = '$.dataList[*].content'

[[font_rules."Ch8VideoEffectSettings.json"]]
font = "mikodacs"
path = '$.dataList[*].texts[*].texts[*].text'